import * as THREE from "three";

import type { CameraPosition } from "@/app/contexts/AppStateContext";

export const SUN_DIRECTION = new THREE.Vector3(-4.374707487564229, -1.3527590872421713, 2.2099736314819878);

export const EARTH_ICOSAHEDRON_RADIUS = 2;
export const EARTH_ICOSAHEDRON_DETAIL = 64;
export const EARTH_AXIAL_TILT_DEGREES = 23.4;

export const ORBIT_SURFACE_CLEARANCE = 0.22;
export const ORBIT_MIN_DISTANCE_FROM_CENTER =
  EARTH_ICOSAHEDRON_RADIUS + ORBIT_SURFACE_CLEARANCE;
export const ORBIT_MAX_DISTANCE = 160;
export const ORBIT_DAMPING_FACTOR = 0.06;
export const ORBIT_TARGET: CameraPosition = [0, 0, 0];
export const ZOOM_WHEEL_RATE = 1 / 450;
export const ZOOM_TRACKPAD_RATE = 1 / 100;
export const ZOOM_MAX_SCALE_PER_FRAME = 2;
export const ZOOM_WHEEL_EASING_DURATION_MS = 200;
export const ZOOM_WHEEL_DELTA_DIVISOR = 4.000244140625;

export const ORBIT_ROTATE_TRACKING_SCALE = EARTH_ICOSAHEDRON_RADIUS * 2;
export const ORBIT_ROTATE_PROXIMITY_DAMPENING = 0.7;

export const CANVAS_TONE_MAPPING = THREE.NoToneMapping;
export const MAX_DEVICE_PIXEL_RATIO = 3;

const EARTH_REAL_RADIUS_KM = 6_371;
const SUN_REAL_RADIUS_KM = 695_700;
const SUN_REAL_DISTANCE_KM = 149_597_870;

const SCENE_SCALE = EARTH_ICOSAHEDRON_RADIUS / EARTH_REAL_RADIUS_KM;

export const SUN_DISTANCE = SUN_REAL_DISTANCE_KM * SCENE_SCALE;
export const SUN_RADIUS = SUN_REAL_RADIUS_KM * SCENE_SCALE;
export const SUN_COLOR = 0xffe599;
export const SUN_EMISSIVE_INTENSITY = 2.5;
export const SUN_GLOW_SCALE = 15;
export const SUN_GLOW_OPACITY = 0.8;
export const SUN_GLOW_FALLOFF = 50.0;

export const CAMERA_FAR = SUN_DISTANCE + SUN_RADIUS * SUN_GLOW_SCALE * 2;

const MOON_REAL_RADIUS_KM = 1_737;
const MOON_REAL_DISTANCE_KM = 384_400;
const MOON_ANTI_SUN_OFFSET_DEGREES = 20;

export const MOON_RADIUS = MOON_REAL_RADIUS_KM * SCENE_SCALE;
export const MOON_DISTANCE = MOON_REAL_DISTANCE_KM * SCENE_SCALE;
export const MOON_ORBITAL_INCLINATION_DEGREES = 5.145;

const SUN_ANGLE_IN_XZ = Math.atan2(SUN_DIRECTION.z, SUN_DIRECTION.x);
export const MOON_ORBITAL_ANGLE_RAD =
  SUN_ANGLE_IN_XZ + Math.PI + (MOON_ANTI_SUN_OFFSET_DEGREES * Math.PI) / 180;

export const GEOJSON_OVERLAY_LINE_COLOR = 0x000000;
export const GEOJSON_OVERLAY_LINE_WIDTH_PX = 2.5;
