import { TIMELINE_BACKDROP_OPACITY } from "./timeline-utils";

const TIMELINE_GRADIENT_FADE_PERCENT = 10;
const TIMELINE_GRADIENT_COLOR = "255, 255, 255";
const TIMELINE_GRADIENT_SOFTENING_RATIO = 0.4;
const TIMELINE_GRADIENT_MID_OPACITY_RATIO = 0.7;
const TIMELINE_GRADIENT_INNER_OPACITY_RATIO = 0.9;
const TIMELINE_GRADIENT_SOFTENING_PERCENT =
  TIMELINE_GRADIENT_FADE_PERCENT * TIMELINE_GRADIENT_SOFTENING_RATIO;
const TIMELINE_GRADIENT_TOP_MID_STOP_PERCENT =
  TIMELINE_GRADIENT_FADE_PERCENT - TIMELINE_GRADIENT_SOFTENING_PERCENT;
const TIMELINE_GRADIENT_TOP_INNER_STOP_PERCENT = TIMELINE_GRADIENT_FADE_PERCENT;
const TIMELINE_GRADIENT_TOP_SOFT_STOP_PERCENT =
  TIMELINE_GRADIENT_FADE_PERCENT + TIMELINE_GRADIENT_SOFTENING_PERCENT;
const TIMELINE_GRADIENT_BOTTOM_SOFT_STOP_PERCENT =
  100 - TIMELINE_GRADIENT_TOP_SOFT_STOP_PERCENT;
const TIMELINE_GRADIENT_BOTTOM_INNER_START_PERCENT =
  100 - TIMELINE_GRADIENT_TOP_INNER_STOP_PERCENT;
const TIMELINE_GRADIENT_BOTTOM_MID_START_PERCENT =
  100 - TIMELINE_GRADIENT_TOP_MID_STOP_PERCENT;
const TIMELINE_GRADIENT_MID_OPACITY =
  TIMELINE_BACKDROP_OPACITY * TIMELINE_GRADIENT_MID_OPACITY_RATIO;
const TIMELINE_GRADIENT_INNER_OPACITY =
  TIMELINE_BACKDROP_OPACITY * TIMELINE_GRADIENT_INNER_OPACITY_RATIO;

export const TIMELINE_BACKGROUND_GRADIENT = `
  linear-gradient(
    to bottom,
    rgba(${TIMELINE_GRADIENT_COLOR}, 0) 0%,
    rgba(${TIMELINE_GRADIENT_COLOR}, ${TIMELINE_GRADIENT_MID_OPACITY}) ${TIMELINE_GRADIENT_TOP_MID_STOP_PERCENT}%,
    rgba(${TIMELINE_GRADIENT_COLOR}, ${TIMELINE_GRADIENT_INNER_OPACITY}) ${TIMELINE_GRADIENT_TOP_INNER_STOP_PERCENT}%,
    rgba(${TIMELINE_GRADIENT_COLOR}, ${TIMELINE_BACKDROP_OPACITY}) ${TIMELINE_GRADIENT_TOP_SOFT_STOP_PERCENT}%,
    rgba(${TIMELINE_GRADIENT_COLOR}, ${TIMELINE_BACKDROP_OPACITY}) ${TIMELINE_GRADIENT_BOTTOM_SOFT_STOP_PERCENT}%,
    rgba(${TIMELINE_GRADIENT_COLOR}, ${TIMELINE_GRADIENT_INNER_OPACITY}) ${TIMELINE_GRADIENT_BOTTOM_INNER_START_PERCENT}%,
    rgba(${TIMELINE_GRADIENT_COLOR}, ${TIMELINE_GRADIENT_MID_OPACITY}) ${TIMELINE_GRADIENT_BOTTOM_MID_START_PERCENT}%,
    rgba(${TIMELINE_GRADIENT_COLOR}, 0) 100%
  )
`;
